# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tensorflow_dev_cert_bootcamp',
                'doc_host': 'https://lohithreddy86.github.io',
                'git_url': 'https://github.com/lohithreddy86/tensorflow_dev_cert_bootcamp',
                'lib_path': 'tensorflow_dev_cert_bootcamp'},
  'syms': { 'tensorflow_dev_cert_bootcamp.core': { 'tensorflow_dev_cert_bootcamp.core.foo': ( 'core.html#foo',
                                                                                              'tensorflow_dev_cert_bootcamp/core.py')}}}
